# Generated by Django 4.2.7 on 2023-11-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup_Form',
            fields=[
                ('UserName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male'), ('u', 'Undisclosed')], max_length=1)),
                ('Graduation', models.CharField(choices=[('b', 'B.Tech'), ('m', 'M.tech/MS'), ('p', 'PhD')], max_length=1)),
            ],
        ),
    ]
